# URL de connexion MongoDB (adaptée à ton réseau)
spring.data.mongodb.uri=mongodb://josue:passer@localhost:27017/to_do

# Permet la création automatique d'index
spring.data.mongodb.auto-index-creation=true

# Permet d'éviter les conflits de beans
spring.main.allow-bean-definition-overriding=true
