spring.application.name=task
# URL de la base de données en mémoire
spring.datasource.url=jdbc:h2:mem:todo_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Activation de la console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuration de JPA (création automatique des tables)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
server.port=8081
