# URL de la base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/to_do
spring.datasource.username=josue
spring.datasource.password=passer
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=9090
