CREATE DATABASE TO_DO;

CREATE TABLE TASK (
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    ACCOMPLISHED BOOLEAN
    USER_ID INT,
    FOREIGN KEY USER_ID REFERENCES USER(ID)
);


CREATE TABLE USER (
    ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255)
);
